name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action when code is pushed to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          # Convert the repository name to lowercase to avoid errors
          repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repo_name/plantgenie-ui:latest .

      # Step 4: Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          # Ensure the repository name is lowercase when pushing
          repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$repo_name/plantgenie-ui:latest
